# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakerName', models.CharField(max_length=300, verbose_name='Nome')),
                ('speakerEmail', models.EmailField(max_length=254, verbose_name='Email')),
                ('speakerFormation', models.CharField(max_length=300, verbose_name='Formação')),
                ('speakerBio', models.TextField(verbose_name='Biografia')),
                ('speakerImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('speakerApproved', models.BooleanField(default=False, verbose_name='Aprovar')),
                ('speakerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
