# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('finishDate', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('formation', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('maxPeople', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('startTime', models.TimeField()),
                ('finishTime', models.TimeField()),
                ('location', models.CharField(max_length=300)),
                ('approved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='events.Event')),
                ('speakers', models.ManyToManyField(related_name='speakers', to='events.Speaker')),
            ],
        ),
    ]
