# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=300, verbose_name='Nome')),
                ('eventDesc', models.TextField(verbose_name='Descrição')),
                ('eventStartDate', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('eventFinishDate', models.DateField(verbose_name='Data de Encerramento')),
                ('eventImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talkName', models.CharField(max_length=300, verbose_name='Nome')),
                ('talkType', models.CharField(max_length=300, verbose_name='Tipo')),
                ('talkDesc', models.TextField(verbose_name='Descrição')),
                ('talkMaxPeople', models.PositiveIntegerField(verbose_name='Quantidade Máxima de Participantes')),
                ('talkDate', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('talkStartTime', models.TimeField(verbose_name='Horário Inicial')),
                ('talkFinishTime', models.TimeField(verbose_name='Horário Final')),
                ('talkLocation', models.CharField(max_length=300, verbose_name='Localização')),
                ('talkApproved', models.BooleanField(default=False, verbose_name='Aprovar')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='events.Event', verbose_name='Evento')),
                ('speakerId', models.ManyToManyField(to='speakers.Speaker', verbose_name='Palestrantes')),
            ],
        ),
    ]
