# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: ifscmeventsapp-95d5b:northamerica-northeast1:ifscmeventsapp

runtime_config:
  python_version: 3
# [END runtime]
